package ed.trabalho.resources.form.model;

import ed.trabalho.model.Person;
import ed.trabalho.model.Academic;
import ed.trabalho.resources.Base;

/**
 * Create or Edit an Academic Formation.
 * @author jorge
 */
public class AcademicCreateEdit extends Base {
  
  /**
   * The current viewing person.
   */
  private Person person;
  
  /**
   * The view frame of person.
   * To manipulate data in lists.
   */
  private BasePerson personInfo; 
  
  /**
   * The academic index to edit.
   */
  private int academicIndex;
    
  /**
   * Instantiates
   */
  public AcademicCreateEdit() {
      initComponents();
  }
    
  /**
   * Set data for creating element.
   * @param personInfo
   */
  public void setData(BasePerson personInfo) {
      this.person = personInfo.getPerson();
      this.personInfo = personInfo;
      this.academicIndex = -1;
      submitSkill.setText("Create");
  }
  
  /**
   * Set data for editing element.
   * @param personInfo
   * @param academicIndex
   */
  public void setData(BasePerson personInfo, int academicIndex) {
    this.person = personInfo.getPerson();
    this.personInfo = personInfo;
    this.academicIndex = academicIndex;
    submitSkill.setText("Update");
    this.populateResource();
  }
  
  /**
   * Populates the form with incoming data.
   */
  private void populateResource(){
    Academic element = this.person.getAcademicList().get(this.academicIndex);

    String year = String.valueOf(element.getYear());
    String description = element.getDescription();
    
    inputYear.setText(year);
    inputDescription.setText(description);
  }
    
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    inputYear = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    submitSkill = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    inputDescription = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel2.setText("Year");

    submitSkill.setText("Create");
    submitSkill.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        submitSkillActionPerformed(evt);
      }
    });

    jLabel3.setText("Description");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(inputYear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(222, 222, 222))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(inputDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(45, 45, 45))))
      .addGroup(layout.createSequentialGroup()
        .addGap(177, 177, 177)
        .addComponent(submitSkill)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(37, 37, 37)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(inputYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(inputDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
        .addComponent(submitSkill)
        .addGap(33, 33, 33))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void submitSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSkillActionPerformed
      //Check is valid
      if(inputYear.getText().isEmpty()){
        this.message("You need to put an year first.");
        return;
      }
      else if(inputDescription.getText().isEmpty()){
        this.message("You need to put a description first.");
        return;
      }
      
      //Message to show at end
      String resultMessage;
      
      //Transform values
      int year = 0;
      String description = "";
      try{
        year = Integer.parseInt(inputYear.getText());
        description = inputDescription.getText();
      }
      catch(Exception e){
        this.message("Invalid parameter");
        return;
      }

      //Is creating
      if(this.academicIndex == -1){
        try{
          //Create element
          Academic newElement = new Academic(year, description);
          
          //Add to person
          this.person.getAcademicList().add(newElement, this.person.getAcademicList().size());
          
          //Updates the list
          this.personInfo.loadAcademic();
   
          resultMessage = "Academic formation was created.";
        }  
        catch(Exception e){
          resultMessage = "Error creating academic formation.";
        } 
      }
      
      //Is editing
      else {
        try{
          //Check has updated
          boolean updated = false;
          
          //Get the original element
          Academic element = this.person.getAcademicList().get(this.academicIndex);
          
          //Check need to change
          if(year != element.getYear()){
            //Update
            element.setYear(year);
            
            updated = true;
          }
          
          if(!description.equals(element.getDescription())){
            //Update
            element.setDescription(description);
            
            updated = true;
          }   
          
          //Updates the list
          if(updated == true){
            this.personInfo.loadAcademic();
            resultMessage = "Academic formation was updated.";
          }
          else
            resultMessage = "Nothing to update.";
        }  
        catch(Exception e){
          resultMessage = "Error updating academic formation.";
        } 
      }
      
      //Dispose the frame and show message
      this.dispose();
      this.message(resultMessage);
    }//GEN-LAST:event_submitSkillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcademicCreateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcademicCreateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcademicCreateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcademicCreateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcademicCreateEdit().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField inputDescription;
  private javax.swing.JTextField inputYear;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JButton submitSkill;
  // End of variables declaration//GEN-END:variables
}
