package ed.trabalho.resources.form;

import ed.trabalho.model.Person;
import ed.trabalho.model.Skill;
import ed.trabalho.resources.frame.PersonInfoFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class AddSkillForm extends javax.swing.JFrame {

    /**
     * Creates new form EditSkill
     */
    public AddSkillForm() {
        initComponents();
    }

    /**
     * The person to add the skill
     */
    private Person person;
    /**
     * The skill list of the person. This is needed to update the list at the end of the adding.
     */
    private javax.swing.JList<String> SkillList; 
    
    /**
     * Method to set the Data
     * @param person the person to add the skill
     * @param SkillList the list of the person skills
     */
    public void setData(Person person, javax.swing.JList<String> SkillList) {
        this.person = person;
        this.SkillList = SkillList;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputSkill = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        createSkill = new javax.swing.JButton();

        jLabel2.setText("New Skill");

        createSkill.setText("Create");
        createSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSkillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(inputSkill, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(createSkill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(createSkill)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSkillActionPerformed
        try{
          if(!inputSkill.getText().isEmpty() && !person.hasSkill(inputSkill.getText())){
            Skill created = new Skill(inputSkill.getText());
            //Adds the skill
            person.getSkillList().add(created, person.getSkillList().size());
            JOptionPane.showMessageDialog(null, "Skill created.");
            
            //Updates the list
            PersonInfoFrame a = new PersonInfoFrame();
            this.SkillList.setListData(a.loadSkill(person));
          }
          else {  
              JOptionPane.showMessageDialog(null, "Skill invalid. Insert a none empty skill that the user does not have");
          }
        }  
        catch(Exception e){
          JOptionPane.showMessageDialog(null, "Error updating the skill.");
        }
    }//GEN-LAST:event_createSkillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSkillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSkillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSkillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSkillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSkillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createSkill;
    private javax.swing.JTextField inputSkill;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
