/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ed.trabalho.resources.form;

import ed.trabalho.model.Person;
import ed.trabalho.model.Skill;
import ed.trabalho.resources.frame.PersonInfoFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class EditSkillForm extends javax.swing.JFrame {

    /**
     * Creates new form EditSkill
     */
    public EditSkillForm() {
        initComponents();
    }

    /**
     * The skill to edit
     */
    private String skill;
    
    /**
     * The person to add the skill
     */
    private Person person;
    
    /**
     * The skill list of the person. This is needed to update the list at the end of the adding.
     */
    private javax.swing.JList<String> SkillList;

    /**
     * Method to set the data
     * @param skill the skill to be edited
     * @param person the person who owns the skill
     * @param SkillList the list of skills of the person
     */
    public void setData(String skill, Person person, javax.swing.JList<String> SkillList) {
        this.skill = skill;
        actualSkill.setText(skill);
        inputSkill.setText(skill);
        this.person = person;
        this.SkillList = SkillList;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        actualSkillLabel = new javax.swing.JLabel();
        actualSkill = new javax.swing.JTextField();
        inputSkill = new javax.swing.JTextField();
        changeSkill = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        actualSkillLabel.setText("Actual Skill");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 12, 0, 0);
        jPanel1.add(actualSkillLabel, gridBagConstraints);

        actualSkill.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 34, 0, 0);
        jPanel1.add(actualSkill, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 34, 0, 0);
        jPanel1.add(inputSkill, gridBagConstraints);

        changeSkill.setText("Save");
        changeSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSkillActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 130, 0, 0);
        jPanel1.add(changeSkill, gridBagConstraints);

        jLabel2.setText("Edit:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 55, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSkillActionPerformed
        try{
          if(!inputSkill.getText().isEmpty() && !this.person.hasSkill(inputSkill.getText())){
            int size = person.getSkillList().size();
            Skill changed = new Skill(inputSkill.getText());
            
            //Searches for the skill
            for (int i=0; i<size; i++) {
                if (person.getSkillList().get(i).getSkill().equals(this.skill))
                    person.getSkillList().change(changed, i);
            }
            JOptionPane.showMessageDialog(null, "Skill updated.");
            
            //Updates the list  
            PersonInfoFrame a = new PersonInfoFrame();
            this.SkillList.setListData(a.loadSkill(person));

          }
          else {
              JOptionPane.showMessageDialog(null, "Insert a none empty skill that the user doesn't have.");
          }
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, "Error updating the skill.");
        }
    }//GEN-LAST:event_changeSkillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSkillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSkillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSkillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSkillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSkillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualSkill;
    private javax.swing.JLabel actualSkillLabel;
    private javax.swing.JButton changeSkill;
    private javax.swing.JTextField inputSkill;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
