/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ed.trabalho.resources.gui;

import ed.trabalho.adt.ReverseNetwork;
import ed.trabalho.helpers.Data;
import ed.trabalho.helpers.Viewer;
import ed.trabalho.json.Pessoa;
import ed.trabalho.model.Person;
import estg.ed.exceptions.ElementNotFoundException;
import estg.ed.interfaces.NetworkADT;
import java.awt.Container;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 * Menu for application using Swing.
 * @author igu
 */
public class JMenu extends javax.swing.JFrame { 
  /**
   * Network with people obtained from JSON input.
   */
  private NetworkADT<Person> network;
  
  /**
   * Creates new form JMenu
   */
  public JMenu() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    fileChooser = new javax.swing.JFileChooser();
    jScrollPane1 = new javax.swing.JScrollPane();
    consoleTextArea = new javax.swing.JTextArea();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    openJson = new javax.swing.JMenuItem();
    Exit = new javax.swing.JMenuItem();
    viewMenu = new javax.swing.JMenu();
    viewNetwork = new javax.swing.JMenuItem();

    fileChooser.setDialogTitle("Choose a File");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Menu");

    consoleTextArea.setEditable(false);
    consoleTextArea.setColumns(20);
    consoleTextArea.setRows(5);
    jScrollPane1.setViewportView(consoleTextArea);

    jMenu1.setText("File");

    openJson.setText("Open JSON");
    openJson.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        openJsonActionPerformed(evt);
      }
    });
    jMenu1.add(openJson);

    Exit.setText("Exit");
    Exit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ExitActionPerformed(evt);
      }
    });
    jMenu1.add(Exit);

    jMenuBar1.add(jMenu1);

    viewMenu.setText("Network");

    viewNetwork.setText("View Network");
    viewNetwork.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viewNetworkActionPerformed(evt);
      }
    });
    viewMenu.add(viewNetwork);

    jMenuBar1.add(viewMenu);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(1243, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Open file chooser to select JSON input.
   * Stores converted JSON info on json attribute.
   * Construct the network after converting JSON.
   * @param evt 
   */
  private void openJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openJsonActionPerformed
    int returnVal = fileChooser.showOpenDialog(this);
    
    //Selected a file
    if(returnVal == JFileChooser.APPROVE_OPTION){
      File file = fileChooser.getSelectedFile();
      
      Pessoa[] data;
      
      //Get JSON data converted into java classes
      try {
        data = Data.readJson(file.getAbsolutePath());
      }
      catch(IOException ex){
        consoleTextArea.setText("Problem acessing file" + file.getAbsolutePath());
        return;
      }
      catch(Exception e){
        consoleTextArea.setText("Error loading file. Is it a valid JSON?");
        return;
      }
    
      //Generates an empty directional network
      //It is reverse, the best cost is from the more weighted edge
      this.network = new ReverseNetwork<>();
      
      //Populate network and peopleList with JSON data
      try {
        Data.populate(data, this.network);
        
      } catch (ElementNotFoundException ex) {
        consoleTextArea.setText("Error populating network with provided data!");
        return;
      }

      //Success
      consoleTextArea.setText("Successfully imported JSON file and populated Network!");
    }
    //Cancelled file input
    else{
      consoleTextArea.setText("File access cancelled by user.");
    }
  }//GEN-LAST:event_openJsonActionPerformed

  private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
    System.exit(0);
  }//GEN-LAST:event_ExitActionPerformed

  private void viewNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNetworkActionPerformed
    try{
      //Generate view
      Viewer viewer = new Viewer();
      viewer.create(this.network);
      viewer.showFrame();

      consoleTextArea.setText("Successfully created network view!");
    }
    catch(Exception e){
      consoleTextArea.setText("Error creating Network View!");
      throw e;
    }
  }//GEN-LAST:event_viewNetworkActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(JMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(JMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(JMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(JMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new JMenu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem Exit;
  private javax.swing.JTextArea consoleTextArea;
  private javax.swing.JFileChooser fileChooser;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JMenuItem openJson;
  private javax.swing.JMenu viewMenu;
  private javax.swing.JMenuItem viewNetwork;
  // End of variables declaration//GEN-END:variables
}
